<!DOCTYPE html>
<html>
<head>
    <title>Туристическое агенство</title>
    <style>
        body {
            background-color: powderblue;
            font-size: 1.5rem;
            margin: 10px 40px;
        }
        h1 {
            font-size: 4rem;
            text-align: center;
            font-weight: bold;
            color: darkorchid;
        }
        hr {
            height: 2.5px;
            border: 0;
            margin: 0;
            background-color: black;
        }
        a {
            text-decoration: none;
            color: black;
            padding: 10px;
            border: 2px solid darkorchid;
            border-radius: 10px;
            background-color: lightsteelblue;
            font-size: 2.5rem;
        }
        div {
            text-align: center;
            margin-top: 65px;
        }
    </style>
</head>
<body>
<h1>Ваш заказ пуст!</h1><hr>
<div><a href="/">Вернуться к просмотру туров</a></div>
</body>
</html>